python3 data-standardization.py
Traceback (most recent call last):
  File "/home/kali/Desktop/script/final-cuts/data-standardization.py", line 270, in <module>
    tracker_df = pd.read_excel(tracker_file_path)
  File "/usr/lib/python3/dist-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pandas/io/excel/_base.py", line 364, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "/usr/lib/python3/dist-packages/pandas/io/excel/_base.py", line 1191, in __init__
    ext = inspect_excel_format(
  File "/usr/lib/python3/dist-packages/pandas/io/excel/_base.py", line 1090, in inspect_excel_format
    zf = zipfile.ZipFile(stream)  # type: ignore[arg-type]
  File "/usr/lib/python3.10/zipfile.py", line 1267, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.10/zipfile.py", line 1334, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
                                               
